FROM python:3.8-slim

WORKDIR /app

COPY app/pdftotext_service.py /app/pdftotext_service.py
COPY app/requirements.txt /app/requirements.txt

RUN apt-get update && apt-get install -y poppler-utils
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "pdftotext_service.py"]
